name: Deploy to Surge

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1.4.2
    - name: Install surge
      run: |
        npm install -g surge
        surge ./ https://usama-bootcamp2020.surge.sh/ --token ${{secrets.TOKEN}}
